### ISSUE TITLE
Implementation on ESP32

### ISSUE THREAD

**Issue by shmrymbd** [m-peko/SecureBLE#1]
Hi,
Any advice how to implement on ESP32?

**Comment by m-peko** [comment]
Hi there,

Sorry for not answering earlier. 
I haven't tried to implement this on ESP32. Have you already tried to run it there?
Also, to be able to implement this stuff on ESP32, you should probably first get Arduino Cryptography Library to run there, if it doesn't already, because this project depends on it. 

Please, let me know the result and, of course, feel free to ask if you need more help. 

Thank you and regards
